/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_token_usage_tokenUsage_getStats_result$schema$value
const _deepseek_ai_dsh_token_usage_tokenUsage_getStats_result$schema = () => (_deepseek_ai_dsh_token_usage_tokenUsage_getStats_result$schema$value ??= z.object({
  'totalConversations': z.number(),
  'totalMessages': z.number(),
  'totalTokens': z.number(),
  'peakTokens': z.number(),
  'maxDurationSec': z.number(),
  'maxDurationText': z.string(),
  'currentStreak': z.number(),
  'longestStreak': z.number(),
  'dailyTokens': z.record(z.string(), z.number()),
  'thinkingLevels': z.object({
  'high': z.number(),
  'medium': z.number(),
  'low': z.number(),
  'off': z.number(),
}),
  'totalToolCalls': z.number(),
  'distinctTools': z.number(),
  'topPlugins': z.array(z.tuple([z.string(), z.number()])),
  'topSkills': z.array(z.tuple([z.string(), z.number()])),
  'totalSkillUses': z.number(),
  'distinctSkills': z.number(),
  'modelBreakdown': z.record(z.string(), z.number()),
  'earliestDate': z.string(),
  'latestDate': z.string(),
  'updatedAt': z.number(),
}))

export const TYPERT = {
  package: 'dsh-token-usage',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-token-usage#tokenUsage/getStats',
      service: 'tokenUsage',
      namespace: 'tokenUsage',
      method: 'getStats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-token-usage/types#TokenUsageSnapshot',
        create: _deepseek_ai_dsh_token_usage_tokenUsage_getStats_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/dsh-token-usage/src/index.ts","line":439,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "只读统计服务：跨全部持久化 session 聚合 token 用量并实时跟随，通过 Typert Remote 暴露给浏览器面板。不创建、不恢复任何 Agent / Session。",
        "summary": "只读统计服务：跨全部持久化 session 聚合 token 用量并实时跟随，通过 Typert Remote 暴露给浏览器面板。不创建、不恢复任何 Agent / Session。",
        "tags": [],
        "jsDoc": "/**\n * 只读统计服务：跨全部持久化 session 聚合 token 用量并实时跟随，通过\n * Typert Remote 暴露给浏览器面板。不创建、不恢复任何 Agent / Session。\n */",
        "key": "tokenUsage",
        "exportName": "TokenUsageService",
        "members": [
          {
            "kind": "method",
            "name": "getStats",
            "signature": "@Remote('getStats') getStats(): TokenUsageSnapshot",
            "summary": "读取当前聚合快照。",
            "jsDoc": "/**\n * 读取当前聚合快照。\n * @returns 全部 session 的 token 用量汇总（纯 JSON）。\n */"
          }
        ],
        "types": [
          {
            "name": "ThinkingLevelCounts",
            "declaration": "export interface ThinkingLevelCounts {\n    high: number;\n    medium: number;\n    low: number;\n    off: number;\n}"
          },
          {
            "name": "TokenUsageSnapshot",
            "declaration": "export interface TokenUsageSnapshot {\n    totalConversations: number;\n    totalMessages: number;\n    totalTokens: number;\n    peakTokens: number;\n    maxDurationSec: number;\n    maxDurationText: string;\n    currentStreak: number;\n    longestStreak: number;\n    dailyTokens: Record<string, number>;\n    thinkingLevels: ThinkingLevelCounts;\n    totalToolCalls: number;\n    distinctTools: number;\n    topPlugins: Array<[string, number]>;\n    topSkills: Array<[string, number]>;\n    totalSkillUses: number;\n    distinctSkills: number;\n    modelBreakdown: Record<string, number>;\n    earliestDate: string;\n    latestDate: string;\n    updatedAt: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
