/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TokenStatsSnapshot } from '@deepseek-ai/dsh-token-stats/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$746f6b656e5374617473 {
    getStats: () => Promise<RemoteResult<TokenStatsSnapshot>>
  }
  interface TypertRemoteMap {
    'tokenStats/getStats': () => Promise<RemoteResult<TokenStatsSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'tokenStats': TypertRemoteNamespace$746f6b656e5374617473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
